stages:
  - build
  - test
  - deploy


test Linux:
  stage: test
  script:
      - tox
  tags:
    - shared-linux
  coverage: '/^TOTAL.*\s+(\d+\%)$/'


test macOS:
  stage: test
  script:
      - tox
  tags:
    - shared-mac


test Windows:
  stage: test
  script:
      - tox
  tags:
    - shared-win


build docs:
  stage: build
  script:
    # create a virtual env
    - py3_venv_name="py-venv-py3"
    - py3_bin=$(which python3)
    - virtualenv -p $py3_bin $py3_venv_name

    # Install requirements for sphinx
    - $py3_venv_name/bin/pip install -r requirements-dev.txt
    - source $py3_venv_name/bin/activate
      
    - cd doc
    - make html
    - cd ..
    
  tags:
    - shared-linux
  artifacts:
    paths:
    - doc/


deploy docs to staging:
  stage: deploy
  script:
    # Note: the group/username directory must already exist on the server before calling this command
    - rsync -avz -e'ssh -v' --numeric-ids --delete doc/build/html/* staging_docs_rsync:{{ cookiecutter.gitlab_group }}/{{ cookiecutter.project_slug }} 2>&1
  tags:
    - docs-staging
  environment:
    name: staging
    url: http://gift-adelie.cs.ucl.ac.uk/staging/{{ cookiecutter.gitlab_group }}/{{ cookiecutter.project_slug }}
  only:
    - master
  dependencies:
    - build docs


deploy docs to production:
  stage: deploy
  script:
    # Note: the group/username directory must already exist on the server before calling this command
    - rsync -avz -e'ssh -v' --numeric-ids --delete doc/build/html/* production_docs_rsync:{{ cookiecutter.gitlab_group }}/{{ cookiecutter.project_slug }} 2>&1
  tags:
    - docs-production
  environment:
    name: production
  only:
    - public
  dependencies:
    - build docs

